### ISSUE TITLE
ikhal: Deleting instances of recurring revent yileds AssertionError

### ISSUE THREAD

**Issue by madduck** [pimutils/khal#793]
I'm running fc5c2bf and just tried to use ikhal to delete one instance of a recurring event. Upon quitting ikhal, I get an assertion error:

```
Traceback (most recent call last):
  File "/home/madduck/code/pimutils/.ve/lib/python3.5/site-packages/khal-0.9.7.dev102+gfc5c2bf-py3.5.egg/khal/ui/__init__.py", line 1346, in start_pane
    loop.run()
  File "/home/madduck/code/pimutils/.ve/lib/python3.5/site-packages/urwid-1.3.1-py3.5-linux-x86_64.egg/urwid/main_loop.py", line 278, in run
    self._run()
  File "/home/madduck/code/pimutils/.ve/lib/python3.5/site-packages/urwid-1.3.1-py3.5-linux-x86_64.egg/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/home/madduck/code/pimutils/.ve/lib/python3.5/site-packages/urwid-1.3.1-py3.5-linux-x86_64.egg/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/home/madduck/code/pimutils/.ve/lib/python3.5/site-packages/urwid-1.3.1-py3.5-linux-x86_64.egg/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/home/madduck/code/pimutils/.ve/lib/python3.5/site-packages/urwid-1.3.1-py3.5-linux-x86_64.egg/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/home/madduck/code/pimutils/.ve/lib/python3.5/site-packages/urwid-1.3.1-py3.5-linux-x86_64.egg/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/home/madduck/code/pimutils/.ve/lib/python3.5/site-packages/urwid-1.3.1-py3.5-linux-x86_64.egg/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/home/madduck/code/pimutils/.ve/lib/python3.5/site-packages/urwid-1.3.1-py3.5-linux-x86_64.egg/urwid/main_loop.py", line 509, in process_input
    something_handled |= bool(self.unhandled_input(k))
  File "/home/madduck/code/pimutils/.ve/lib/python3.5/site-packages/urwid-1.3.1-py3.5-linux-x86_64.egg/urwid/main_loop.py", line 555, in unhandled_input
    return self._unhandled_input(input)
  File "/home/madduck/code/pimutils/.ve/lib/python3.5/site-packages/khal-0.9.7.dev102+gfc5c2bf-py3.5.egg/khal/ui/base.py", line 204, in on_key_press
    self.backtrack()
  File "/home/madduck/code/pimutils/.ve/lib/python3.5/site-packages/khal-0.9.7.dev102+gfc5c2bf-py3.5.egg/khal/ui/base.py", line 189, in backtrack
    cb(data)
  File "/home/madduck/code/pimutils/.ve/lib/python3.5/site-packages/khal-0.9.7.dev102+gfc5c2bf-py3.5.egg/khal/ui/__init__.py", line 1102, in cleanup
    self.collection.update(event)
  File "/home/madduck/code/pimutils/.ve/lib/python3.5/site-packages/khal-0.9.7.dev102+gfc5c2bf-py3.5.egg/khal/khalendar/khalendar.py", line 165, in update
    assert event.etag
AssertionError
```

The change is not saved, i.e. the event is not updated on disk.

Looking at [the code, while running](https://github.com/pimutils/khal/blob/master/khal/khalendar/khalendar.py#L165), `event` is a `khal.khalendar.event.LocalizedEvent`, but `event.etag` is `None`.

**Comment by modelm** [comment]
I also experienced this bug in version `0.10.0`:

```Traceback (most recent call last):
  File "/usr/local/Cellar/khal/0.10.0/libexec/lib/python3.7/site-packages/khal/ui/__init__.py", line 1346, in start_pane
    loop.run()
  File "/usr/local/Cellar/khal/0.10.0/libexec/lib/python3.7/site-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/usr/local/Cellar/khal/0.10.0/libexec/lib/python3.7/site-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/usr/local/Cellar/khal/0.10.0/libexec/lib/python3.7/site-packages/urwid/main_loop.py", line 788, in run
    self._loop()
  File "/usr/local/Cellar/khal/0.10.0/libexec/lib/python3.7/site-packages/urwid/main_loop.py", line 825, in _loop
    self._watch_files[fd]()
  File "/usr/local/Cellar/khal/0.10.0/libexec/lib/python3.7/site-packages/urwid/raw_display.py", line 404, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/local/Cellar/khal/0.10.0/libexec/lib/python3.7/site-packages/urwid/raw_display.py", line 502, in parse_input
    callback(processed, processed_codes)
  File "/usr/local/Cellar/khal/0.10.0/libexec/lib/python3.7/site-packages/urwid/main_loop.py", line 411, in _update
    self.process_input(keys)
  File "/usr/local/Cellar/khal/0.10.0/libexec/lib/python3.7/site-packages/urwid/main_loop.py", line 517, in process_input
    something_handled |= bool(self.unhandled_input(k))
  File "/usr/local/Cellar/khal/0.10.0/libexec/lib/python3.7/site-packages/urwid/main_loop.py", line 563, in unhandled_input
    return self._unhandled_input(input)
  File "/usr/local/Cellar/khal/0.10.0/libexec/lib/python3.7/site-packages/khal/ui/base.py", line 204, in on_key_press
    self.backtrack()
  File "/usr/local/Cellar/khal/0.10.0/libexec/lib/python3.7/site-packages/khal/ui/base.py", line 189, in backtrack
    cb(data)
  File "/usr/local/Cellar/khal/0.10.0/libexec/lib/python3.7/site-packages/khal/ui/__init__.py", line 1102, in cleanup
    self.collection.update(event)
  File "/usr/local/Cellar/khal/0.10.0/libexec/lib/python3.7/site-packages/khal/khalendar/khalendar.py", line 167, in update
    assert event.etag
AssertionError
```

**Comment by evan-goode** [comment]
I'm also experiencing this bug in version 0.10.1. My traceback looks pretty much the same as the above two.

**Comment by deep-42-thought** [comment]
Any chance on getting this fixed? What's the holdback?
I have no idea, how the `.ics` file should look for a recurring event, where only one occurrence was removed.

**Comment by ephase** [comment]
After some investigations, I found that event return by`self.collection.get_event()` in `cleanup()` doesn't contain the `etag`, I need to test a bit more and investigate.

For now, i found a little workaround  by modifing `cleanup()` like this:

```python
    def cleanup(self, data):
        """delete all events marked for deletion"""
        for part in self._deleted[ALL]:
            account, href, etag = part.split('\n', 2)
            self.collection.delete(href, etag, account)
        for part, rec_id in self._deleted[INSTANCES]:
            account, href, etag = part.split('\n', 2)
            event = self.collection.get_event(href, account)
            event.delete_instance(rec_id)
            event.etag = etag
            self.collection.update(event)
```

**Comment by geier** [comment]
@ephase thanks for taking care of this! If you need any help, I'll try to be more responsive than in the past.

**Comment by ephase** [comment]
@geier thanks a lot, I'll try to be more present too and work weekly on khal :)

**Comment by evan-goode** [comment]
@ephase thanks for the workaround! Fixes the issue for me as far as I can tell

**Comment by ephase** [comment]
@evan-goode thanks for testing it, now I try to investigate deeply in the code.

**Comment by ahillio** [comment]
```
diff --git a/ui/__init__.py b/ui/__init__.py
index d0efa68..395c450 100644
--- a/ui/__init__.py
+++ b/ui/__init__.py
@@ -1101,6 +1101,7 @@ class ClassicView(Pane):
             account, href, etag = part.split('\n', 2)
             event = self.collection.get_event(href, account)
             event.delete_instance(rec_id)
+            event.etag = etag
             self.collection.update(event)
 
     def keypress(self, size, key):

```

Is working for me too :)

**Comment by deep-42-thought** [comment]
This solves the issue for me, if I delete a single event. However, when I deleted multiple events (3 or 4, I think - 2 of which from the same recurring event), I got:
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/khal/ui/__init__.py", line 1349, in start_pane
    loop.run()
  File "/usr/lib/python3.7/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/usr/lib/python3.7/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/usr/lib/python3.7/site-packages/urwid/main_loop.py", line 790, in run
    self._loop()
  File "/usr/lib/python3.7/site-packages/urwid/main_loop.py", line 827, in _loop
    self._watch_files[fd]()
  File "/usr/lib/python3.7/site-packages/urwid/raw_display.py", line 417, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python3.7/site-packages/urwid/raw_display.py", line 515, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3.7/site-packages/urwid/main_loop.py", line 412, in _update
    self.process_input(keys)
  File "/usr/lib/python3.7/site-packages/urwid/main_loop.py", line 519, in process_input
    something_handled |= bool(self.unhandled_input(k))
  File "/usr/lib/python3.7/site-packages/urwid/main_loop.py", line 565, in unhandled_input
    return self._unhandled_input(input)
  File "/usr/lib/python3.7/site-packages/khal/ui/base.py", line 204, in on_key_press
    self.backtrack()
  File "/usr/lib/python3.7/site-packages/khal/ui/base.py", line 189, in backtrack
    cb(data)
  File "/usr/lib/python3.7/site-packages/khal/ui/__init__.py", line 1105, in cleanup
    self.collection.update(event)
  File "/usr/lib/python3.7/site-packages/khal/khalendar/khalendar.py", line 171, in update
    event.etag = self._storages[event.calendar].update(event.href, event, event.etag)
  File "/usr/lib/python3.7/site-packages/khal/khalendar/vdir.py", line 246, in update
    raise WrongEtagError(etag, actual_etag)
khal.khalendar.vdir.WrongEtagError: [Errno 1602831804074305280.000000000] 1602831835764114944.000000000
```

**Comment by deep-42-thought** [comment]
ok, just checked by deleting another slice of events:
If I delete two neighbouring events of one recurring event, only the first of both gets deleted.

**Comment by ephase** [comment]
Thanks for sharing me this particular case because I didn't test it with 
my (ugly) workaround.

That's I said previously, this issue need more investigation, I'm on it 

Thanks all for testing 😀`:

-- 
Yorick Barbanneau
--
https://www.xieme-art.org
https://toot.aquilenet.fr/@ephase

**Comment by jcjgraf** [comment]
Any update on this bug?

**Comment by miku86** [comment]
Any update on this bug?

**Comment by ahillio** [comment]
I'm pretty sure this has been fixed.  Update to a modern/current version.

**Comment by miku86** [comment]
I'm running `Version: 0.10.4-2` on Arch Linux,
and it is not fixed.

**Comment by rbugajewski** [comment]
> I'm running the newest version, `Version: 0.10.4-2` on Arch Linux, and it is not fixed.

You run Arch BTW? So nice :rofl: 

I’m on the following `ikhal` version and still experience the bug, too:

```
% ikhal --version
ikhal, version 0.10.4
```

**Comment by duckunix** [comment]
Just tried on 0.10.5, and the issue is still present.
```
[don@eve:~] $ ikhal --version
ikhal, version 0.10.5
```

**Comment by geier** [comment]
Could you try if master branch fixes the issue?
